version: "3"

services:
  myfoil:
    container_name: myfoil
    image: snwaine/myfoil:v2
    environment:
      # For write permission in config directory
      - PUID=1000
      - PGID=1000
    volumes:
      - /your/game/directory:/games
      - ./config:/app/config
    ports:
      - "8465:8465"
